/* Generated By:JavaCC: Do not edit this line. DartGramaticaConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DartGramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SOMA = 1;
  /** RegularExpression Id. */
  int SUBTRACAO = 2;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 3;
  /** RegularExpression Id. */
  int DIVISAO = 4;
  /** RegularExpression Id. */
  int IGUAL = 5;
  /** RegularExpression Id. */
  int COMPARACAO = 6;
  /** RegularExpression Id. */
  int DIFERENTE = 7;
  /** RegularExpression Id. */
  int MAIOR = 8;
  /** RegularExpression Id. */
  int MENOR = 9;
  /** RegularExpression Id. */
  int MAIORIGUAL = 10;
  /** RegularExpression Id. */
  int MENORIGUAL = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int OR = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int IMPORT = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int FOR = 18;
  /** RegularExpression Id. */
  int IN = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int RETURN = 23;
  /** RegularExpression Id. */
  int PRINT = 24;
  /** RegularExpression Id. */
  int ENTRADA = 25;
  /** RegularExpression Id. */
  int TIPO = 26;
  /** RegularExpression Id. */
  int INTEIRO = 27;
  /** RegularExpression Id. */
  int REAL = 28;
  /** RegularExpression Id. */
  int STRING = 29;
  /** RegularExpression Id. */
  int COMENTARIO = 30;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 31;
  /** RegularExpression Id. */
  int ESPACO = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"import \"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"in\"",
    "\"while\"",
    "\"true\"",
    "\"false\"",
    "\"return\"",
    "\"print\"",
    "\"stdin.readLineSync()\"",
    "<TIPO>",
    "<INTEIRO>",
    "<REAL>",
    "<STRING>",
    "<COMENTARIO>",
    "<IDENTIFICADOR>",
    "<ESPACO>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
  };

}
